### ISSUE TITLE
There is no ability to perform POST with binary body.

### ISSUE THREAD

**Issue by Ramzec** [garyburd/go-oauth#26]
In terms of "http" package there is only ability to do PostForm. Correct?
If so, could you please answer is it possible to implement non-form Post by using go-oauth ?

**Comment by garyburd** [comment]
Use [SignForm](https://godoc.org/github.com/garyburd/go-oauth/oauth#Client.SignForm) to sign the request and add the updated form as a query string or use [SetAuthorizationHeader](https://godoc.org/github.com/garyburd/go-oauth/oauth#Client.SetAuthorizationHeader) to add an authorization header.

In both cases, use the http Client directly instead of using the [Post](https://godoc.org/github.com/garyburd/go-oauth/oauth#Client.Post) helper function.

**Comment by garyburd** [comment]
Here's how post the  binary body `requestBody` with query parameters `form`:

        req, err := http.NewRequest("POST", u, requestBody)
	if err != nil {
		// handle error
	}
	if err := c.SetAuthorizationHeader(req.Header, credentials, "POST", req.URL, form); err != nil {
		handle error
	}
	req.URL.RawQuery = form.Encode()
	resp, err := client.Do(req)
